# This workflow to run the test suite for CWInPy (based on the default workflow)
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ github_workflow ]
  pull_request:
    branches: [ github_workflow ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update Ubuntu packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y --no-install-recommends libblas3 libblas-dev liblapack3 liblapack-dev libatlas3-base libatlas-base-dev cmake build-essential gfortran texlive texlive-latex-extra dvipng libgslcblas0 libgsl-dev
    - name: Install Miniconda
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda create -q -n test-environment-python${{ matrix.python-version }} python=${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda activate test-environment-python${{ matrix.python-version }}
        python -m pip install --upgrade pip
        conda install -y numpy"<1.20" matplotlib scipy astropy
        conda install -c anaconda coverage configargparse future libopenblas
        conda install -c numba numba
        conda install -c conda-forge black gwpy lalsuite bilby bilby_pipe lintegrate pycondor gwosc dynesty
        pip install pyerfa
        if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
        pip install -e .
    - name: Run test suite
      run: |
        # disable numba jit for code coverage (see https://stackoverflow.com/a/26894553/1862861)
        export NUMBA_DISABLE_JIT=1
        pytest --cov=cwinpy
    - name: Run code cov
      run: |
        codecov
